global:
  podLabels:
    sidecar.istio.io/inject: "true"

server:
  insecure: true
  service:
    type: ClusterIP

configs:
  params:
    server.insecure: "true"
  cm:
    url: "https://argocd.fetdevops.com"
    application.instanceLabelKey: argocd.argoproj.io/instance