apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamfet/online-boutique-gitops.git
    targetRevision: HEAD
    path: /overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true #creates namespace specified in "destination" if it does not exist, otherwise applicatin will fail to sync
