global:
  enabled: true

server:
  enabled: true
  
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: gp2
  
  standalone:
    enabled: false
  
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        seal "awskms" {
          region = "us-east-1"
          kms_key_id = "alias/vault-unseal-key"
        }
        service_registration "kubernetes" {}

ui:
  enabled: true
  serviceType: ClusterIP

injector:
  enabled: false