name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true

permissions:
  id-token: write
  contents: read

env:
  TF_LOG: INFO
  AWS_REGION: us-east-1

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'
    environment: dev
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: |
          # Initialize with remote backend
          terraform init

      - name: Release state lock
        run: terraform force-unlock -force 67f3b23d-fced-793b-807f-0ec4ae73a5d1
        continue-on-error: true

      - name: Remove ArgoCD applications
        run: |
          aws eks update-kubeconfig --name ama-shop-eks-cluster --region ${{ env.AWS_REGION }}
          kubectl delete applications --all -n argocd || true
          kubectl delete appprojects --all -n argocd || true
        continue-on-error: true

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -var="user_for_admin_role=${{ secrets.ADMIN_USER_ARN }}" \
            -var="user_for_dev_role=${{ secrets.DEV_USER_ARN }}" \
            -auto-approve
            
      - name: Clean up backend
        run: |
          cd backend
          terraform init
          terraform destroy -auto-approve