name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, Linux]  # Make sure these match your runner labels
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello from self-hosted runner"
